version: '2'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:4.7.2
    restart: always
    volumes:
      - ./wordpress:/var/www/html
      - ./01.conf:/etc/apache2/sites-enabled/0000-default.conf
      - ./ssl/certs:/etc/ssl/certs
      - ./ssl/apache-selfsigned.key:/etc/ssl/apache-selfsigned.key

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: test
    ports:
      - 80:80 # Expose http and https
      - 443:443
    networks:
      - back
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: test
    networks:
      - back
networks:
  back:
volumes:
  db_data:
